version: 2
project_name: clispot
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
before:
  hooks:
    - ./scripts/manpages.sh
    - ./scripts/completions.sh
builds:
  - id: clispot
    binary: clispot
    main: .
    ldflags: -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=1
archives:
  -
    ids:
      - clispot
    format_overrides:
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
nfpms:
  - ids:
      - clispot
    vendor: kumneger0
    homepage:  https://github.com/kumneger0/clispot
    maintainer: "Kumneger wondimu <Kumnegerwondimu@gmail.com>"
    description: "CLI-based Telegram client"
    license: GPL-3.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./manpages/clispot.1.gz
        dst: /usr/share/man/man1/clispot.1.gz
        file_info:
          mode: 0644
      - src: ./completions/clispot.bash
        dst: /usr/share/bash-completion/completions/clispot
        file_info:
          mode: 0644
      - src: ./completions/clispot.fish
        dst: /usr/share/fish/vendor_completions.d/clispot.fish
        file_info:
          mode: 0644
      - src: ./completions/clispot.zsh
        dst:  /usr/share/zsh/vendor-completions/_clispot
        file_info:
          mode: 0644
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
